/**
 * Report generator - Generate reports in various formats
 */

import { v4 as uuidv4 } from 'uuid';
import { generatePDF } from './pdf.js';
import type { Report, ReportOptions } from '../core/index.js';

export interface ReportResult extends Report {
  pdfPath?: string;
}

export async function generateReport(
  researchId: string | undefined,
  options: ReportOptions
): Promise<ReportResult> {
  const id = researchId ?? uuidv4();
  const format = options.format ?? 'markdown';

  // Generate content based on format
  let content: string;
  let pdfPath: string | undefined;

  if (format === 'pdf') {
    // For PDF, generate markdown first then convert
    content = generateMarkdownReport(id);

    if (options.outputPath) {
      await generatePDF(content, options.outputPath, {
        title: `Research Report ${id}`,
        author: 'SciClaw',
      });
      pdfPath = options.outputPath;
    }
  } else if (format === 'html') {
    content = generateHTMLReport(id);
  } else {
    content = generateMarkdownReport(id);
  }

  return {
    id,
    title: `Research Report ${id}`,
    content,
    format,
    createdAt: new Date(),
    pdfPath,
  };
}

function generateMarkdownReport(id: string): string {
  return `# Research Report

**ID**: ${id}
**Generated**: ${new Date().toISOString()}

## Summary

[Research summary would appear here]

## Sources

- [Source 1](#)
- [Source 2](#)

---

*Generated by SciClaw v2.0.0-beta.1*
`;
}

function generateHTMLReport(id: string): string {
  const markdown = generateMarkdownReport(id);
  // Simple markdown to HTML conversion
  return markdown
    .replace(/^# (.+)$/gm, '<h1>$1</h1>')
    .replace(/^## (.+)$/gm, '<h2>$1</h2>')
    .replace(/^### (.+)$/gm, '<h3>$1</h3>')
    .replace(/^- (.+)$/gm, '<li>$1</li>')
    .replace(/\*\*(.+?)\*\*/g, '<strong>$1</strong>')
    .replace(/\n\n/g, '</p><p>')
    .replace(/\n/g, '<br>');
}

export async function generatePDFReport(
  researchId: string | undefined,
  outputPath: string
): Promise<{ id: string; path: string }> {
  const id = researchId ?? uuidv4();
  const content = generateMarkdownReport(id);

  await generatePDF(content, outputPath, {
    title: `Research Report ${id}`,
    author: 'SciClaw',
  });

  return { id, path: outputPath };
}

export { generateReport as default };
